name: Main CI workflow

on: [push]

jobs:
  run-ci:
    name: Run Type Check & Linters
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Check types
        run: npm run tsc

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
